// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/testComp/A.vue')['default']
    B: typeof import('./src/components/testComp/B.vue')['default']
    C: typeof import('./src/components/testComp/C.vue')['default']
    Code: typeof import('./src/components/dialog/Code.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    Container: typeof import('./src/components/dialog/Container.vue')['default']
    DCol: typeof import('vue-devui/col/index.es.js')['Col']
    DragBox: typeof import('./src/components/helper/DragBox.vue')['default']
    DRow: typeof import('vue-devui/row/index.es.js')['Row']
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditorTree: typeof import('./src/components/EditorTree.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTab: typeof import('element-plus/es')['ElTab']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    Load: typeof import('./src/components/dialog/Load.vue')['default']
    ModuleList: typeof import('./src/components/ModuleList.vue')['default']
    PageAdmin: typeof import('./src/components/PageAdmin.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    Render: typeof import('./src/components/Render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/dialog/Service.vue')['default']
  }
}
